version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'usrpwd'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    expose:
      - '8080'
    networks:
      - mysql-compose-network

volumes:
  my-db:

networks:
  mysql-compose-network:
    driver: bridge